# Generated by Django 4.1.7 on 2023-07-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
