# Generated by Django 4.1.7 on 2023-06-27 10:53

import business.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=120)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('founded_in', models.DateTimeField(blank=True, null=True)),
                ('employee_count', models.PositiveIntegerField()),
                ('id_number', models.CharField(max_length=13, verbose_name='ID Number')),
                ('kra_pin', models.CharField(max_length=42, verbose_name='kra pin number')),
                ('bs_reg_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Business registration number')),
                ('bs_permit_number', models.CharField(max_length=100, verbose_name='Business Permit Number')),
                ('ceritificate_of_registration', models.FileField(upload_to=None, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('id_attachment', models.FileField(upload_to=None, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('business_permit', models.FileField(upload_to=business.models.upload_location, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('kra_pin_attachment', models.FileField(upload_to=None, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('social_media_links', models.JSONField(blank=True, default=dict, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
            ],
        ),
    ]
