# Generated by Django 4.1.7 on 2023-06-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0001_initial'),
        ('healthandbeauty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_beauty',
            name='packaging',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appliances.package'),
        ),
        migrations.AddField(
            model_name='health_beauty',
            name='per',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appliances.per'),
        ),
    ]
