# Generated by Django 4.1.7 on 2023-09-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('is_city', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='region',
            name='county',
        ),
        migrations.RemoveField(
            model_name='region',
            name='subcounty',
        ),
    ]
