# Generated by Django 4.1.7 on 2023-09-17 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phoneandtablet', '0002_remove_phone_tablet_region_phone_tablet_locality'),
        ('healthandbeauty', '0004_health_beauty_locality'),
        ('fashion', '0003_fashion_locality'),
        ('homeandoffice', '0003_home_office_locality'),
        ('sporting', '0002_remove_sport_gooding_region_sport_gooding_locality'),
        ('locations', '0002_locality_remove_region_county_and_more'),
        ('mechanic', '0002_remove_mechanic_region_mechanic_locality'),
        ('appliances', '0003_appliance_locality'),
        ('otherservices', '0002_remove_other_service_region_other_service_locality'),
        ('computersandaccessories', '0003_computing_locality'),
        ('otherproducts', '0002_remove_other_product_region_other_product_locality'),
        ('baby_items', '0003_babyproduct_locality'),
        ('beauty', '0003_beauty_locality'),
        ('groceries', '0003_grocery_locality'),
        ('cateringandevent', '0003_catering_event_locality'),
        ('transportation', '0002_remove_transport_region_transport_locality'),
        ('gaming', '0003_gaming_locality'),
        ('computerandit', '0003_computer_it_locality'),
        ('cleaning', '0003_cleaning_locality'),
        ('tvandaudio', '0002_remove_tv_audio_region_tv_audio_locality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='locality',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_Localities', to='locations.county'),
        ),
        migrations.AddField(
            model_name='locality',
            name='subcounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounty_Localities', to='locations.subcounty'),
        ),
    ]
